"""Prepare arrays, execute artifact-tool chunks, package their unchanged OOXML.

This module does not author spreadsheet cells: all cells and their final row
addresses are generated by export_workbooks.mjs. Standard-library zipfile only
joins already-authored sheetData rows after checking common styles/strings.
Openpyxl is used exclusively for reading the final file.
"""
from __future__ import annotations
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import time
import threading
import zipfile
import xml.etree.ElementTree as ET
from xml.sax.saxutils import escape
from concurrent.futures import ThreadPoolExecutor
from decimal import Decimal, ROUND_HALF_UP
import numpy as np
import openpyxl


def sha(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for b in iter(lambda: f.read(2**20), b""):
            h.update(b)
    return h.hexdigest()


def rounded4(array):
    a = np.asarray(array, dtype=float)
    scaled = np.abs(a) * 1e4
    out = np.sign(a) * np.floor(scaled + 0.5) / 1e4
    ties = np.abs(scaled - np.floor(scaled) - 0.5) <= 1e-8
    for idx in zip(*np.where(ties)):
        out[idx] = float(Decimal(str(float(a[idx]))).quantize(Decimal("0.0001"), rounding=ROUND_HALF_UP))
    return out


def verify_common_parts(base, part):
    for common in ["xl/styles.xml", "xl/sharedStrings.xml"]:
        if part.read(common)!=base.read(common):
            raise ValueError(f"Chunk metadata differs: {common}")
    # Each export legitimately creates fresh relationship IDs. Keep the first
    # package's workbook and .rels unchanged; compare their resolved meaning.
    def signature(z):
        rel=ET.fromstring(z.read("xl/_rels/workbook.xml.rels"))
        targets={e.attrib["Id"]:e.attrib["Target"] for e in rel}
        book=ET.fromstring(z.read("xl/workbook.xml"))
        main="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
        relation="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
        sheets=[(e.attrib["name"],targets[e.attrib[f"{{{relation}}}id"]]) for e in book.findall(f"{{{main}}}sheets/{{{main}}}sheet")]
        return sheets,sorted((e.attrib["Type"],e.attrib["Target"]) for e in rel)
    if signature(base)!=signature(part):
        raise ValueError("Chunk workbook/sheet relationship meaning differs")


def combine_chunks(chunks, destination):
    """Transport artifact-authored XML rows verbatim; never calculate a cell."""
    destination = Path(destination)
    temp = destination.with_suffix(".partial.xlsx")
    row_re = re.compile(rb'<x:row\b[^>]*\br="(\d+)"[^>]*(?:/>|>.*?</x:row>)', re.S)
    evidence = {"method": "artifact-tool authoring; verbatim sheetData row packaging", "chunks": [], "sheets": {}}
    with zipfile.ZipFile(chunks[0][2]) as base, zipfile.ZipFile(temp, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6, allowZip64=True) as final:
        names = base.namelist()
        sheets = [n for n in names if re.fullmatch(r"xl/worksheets/sheet[12]\.xml", n)]
        for name in names:
            if name not in sheets:
                final.writestr(name, base.read(name))
        for sheet in sheets:
            previous = 0
            count = 0
            with final.open(sheet, "w", force_zip64=True) as output:
                base_xml = base.read(sheet)
                before, rest = base_xml.split(b"<x:sheetData>", 1)
                _, after = rest.split(b"</x:sheetData>", 1)
                # artifact-tool currently omits dimension. Reject a future
                # per-chunk dimension rather than silently authoring metadata.
                if b"<x:dimension" in before:
                    raise ValueError("Unexpected per-chunk dimension metadata")
                output.write(before + b"<x:sheetData>")
                for lo, hi, filename in chunks:
                    with zipfile.ZipFile(filename) as part:
                        verify_common_parts(base,part)
                        xml = part.read(sheet)
                    expected = lo + 1
                    for m in row_re.finditer(xml):
                        row = int(m[1])
                        if row == 1 and previous == 0:
                            output.write(m[0]); previous = 1; count += 1
                        elif lo + 1 <= row <= hi:
                            if row != expected or row != previous + 1:
                                raise ValueError(f"Missing/duplicate row {row}; expected {expected}")
                            output.write(m[0]); previous = row; expected += 1; count += 1
                    if expected != hi + 1:
                        raise ValueError(f"Incomplete chunk: {filename}")
                output.write(b"</x:sheetData>" + after)
            evidence["sheets"][sheet] = {"total_rows_including_header": count, "last_row": previous}
    temp.replace(destination)
    for lo, hi, p in chunks:
        evidence["chunks"].append({"source_index_lo": lo, "source_index_hi_exclusive": hi, "sha256": sha(p), "bytes": Path(p).stat().st_size})
    evidence["final_sha256"] = sha(destination)
    return evidence


def validate_q2(path, time_s, profiles, radius_cm):
    report = {"file": str(path), "sha256": sha(path), "rounding": "decimal ROUND_HALF_UP, 4 places; time unrounded", "sheets": {}}
    wb = openpyxl.load_workbook(path, read_only=True, data_only=False)
    if wb.sheetnames != ["温度", "水分浓度"]:
        raise ValueError("Template sheet names/order changed")
    for name, component in [("温度", 0), ("水分浓度", 1)]:
        s = wb[name]
        rows = s.iter_rows(values_only=True)
        header = next(rows)
        if header != tuple(["时间\\到药材中心的距离", *radius_cm]):
            raise ValueError(f"Unexpected header {header}")
        expected = rounded4(profiles[1:, :, component])
        mismatch = 0; maxdiff = 0.0; n = 0; badtime = 0; badtypes = 0
        for n, row in enumerate(rows, 1):
            if n >= len(time_s):
                raise ValueError("Unexpected trailing row")
            if len(row) != 22:
                raise ValueError(f"Wrong column count at row {n+1}")
            badtime += row[0] != float(time_s[n])
            badtypes += sum(not isinstance(v, (int, float)) for v in row)
            d = np.abs(np.asarray(row[1:], dtype=float) - expected[n-1])
            mismatch += int(np.count_nonzero(d)); maxdiff = max(maxdiff, float(d.max()))
        report["sheets"][name] = {"data_rows": n, "expected_data_rows": len(time_s)-1, "numeric_cells_compared": n*21, "time_mismatches": badtime, "value_mismatches": mismatch, "max_abs_difference_after_rounding": maxdiff, "non_numeric_cells": badtypes, "first_time_s": float(time_s[1]), "last_time_s": float(time_s[-1])}
        if n != len(time_s)-1 or mismatch or badtime or badtypes:
            raise ValueError(json.dumps(report["sheets"][name]))
    wb.close()
    report["passed"] = True
    return report


def validate_q4(path, source):
    indexes=[i for i,t in enumerate(source["time_s"]) if t>0]
    expected_times=np.array([source["time_s"][i] for i in indexes])
    if not np.array_equal(expected_times[:-1],np.arange(60,expected_times[-1],60)):
        raise ValueError("Q4 time grid is not every 60 s plus final time")
    wb=openpyxl.load_workbook(path,read_only=True,data_only=False)
    if wb.sheetnames != ["Sheet1"]:
        raise ValueError("Q4 template sheet name changed")
    it=wb["Sheet1"].iter_rows(max_col=25,values_only=True)
    header=next(it)
    if header[:23]!=tuple(["时间\\到药材中心的距离",*[j/10 for j in range(21)],"药材表面"]):
        raise ValueError("Q4 template core header changed")
    errors=[]; cells=0; blanks=0; coincident=0; radius_error=0.0; n=0
    for n,row in enumerate(it,1):
        if n>len(indexes):
            raise ValueError("Q4 unexpected trailing data row")
        i=indexes[n-1]; radius=source["radius_m"][i]
        if row[0]!=source["time_s"][i]:
            errors.append([n+1,"time"])
        want=source["C_fixed"][i]+[source["C_surface"][i]]
        expected=[None if x is None else float(Decimal(str(x)).quantize(Decimal('0.0001'),rounding=ROUND_HALF_UP)) for x in want]
        if list(row[1:23])!=expected:
            errors.append([n+1,"value"])
        for j in range(21):
            outside=j/1000>radius+1e-12
            if (row[j+1] is None)!=outside:
                errors.append([n+1,j+2,"domain_mask"])
            if outside: blanks+=1
            else: cells+=1
            if abs(j/1000-radius)<=1e-12:
                coincident+=1
                if row[j+1]!=row[22]: errors.append([n+1,j+2,"surface_coincidence"])
        cells+=1
        if row[23] is not None: errors.append([n+1,"spacer"])
        radius_error=max(radius_error,abs(row[24]-radius*100))
    wb.close()
    report={"file":str(path),"sha256":sha(path),"rounding":"decimal ROUND_HALF_UP, 4 places; time unrounded","data_rows":n,"expected_data_rows":len(indexes),"numeric_moisture_cells_compared":cells,"outside_domain_blank_cells":blanks,"surface_coincidences_checked":coincident,"time_grid":"60 s, 120 s, ... plus actual final time", "first_time_s":float(expected_times[0]),"last_time_s":float(expected_times[-1]),"radius_metadata_max_abs_error_cm":radius_error,"errors":errors[:100],"passed":n==len(indexes) and not errors and radius_error<1e-12}
    if not report["passed"]: raise ValueError(json.dumps(report))
    return report


def main():
    p=argparse.ArgumentParser()
    p.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    p.add_argument("--q2-npz", type=Path)
    p.add_argument("--q4-json", type=Path)
    p.add_argument("--out-dir",type=Path,help="New delivery directory for a cold-start rebuild; refuses to overwrite an existing formal XLSX")
    p.add_argument("--chunk-rows", type=int, default=10000)
    p.add_argument("--font", default="Arial")
    p.add_argument("--resume", action="store_true")
    p.add_argument("--workers",type=int,choices=[1,2],default=2)
    a=p.parse_args()
    root=a.root.resolve(); source_delivery=root if (root/"source/export_workbooks.mjs").exists() else root/"q4_complete_delivery/v1"
    delivery=a.out_dir.resolve() if a.out_dir else source_delivery
    for relative in ["output","validation","q123_closeout"]:
        (delivery/relative).mkdir(parents=True,exist_ok=True)
    targets=[]
    if a.q4_json: targets.append(delivery/"output/result4.xlsx")
    if a.q2_npz: targets.append(delivery/"q123_closeout/result2.xlsx")
    for target in targets:
        if target.exists(): raise FileExistsError(f"Refusing to overwrite {target}; choose a new --out-dir")
    temp=Path(os.environ.get("DRYING_WORKBOOK_TEMP", str(Path.cwd()/"workbook_temp"))); temp.mkdir(parents=True,exist_ok=True)
    node=os.environ["CODEX_PRIMARY_RUNTIME_NODE"]
    modules=Path(os.environ["CODEX_PRIMARY_RUNTIME_NODE_MODULES"])
    if not (temp/"node_modules").exists():
        (temp/"node_modules").symlink_to(modules, target_is_directory=True)
    shutil.copyfile(source_delivery/"source/export_workbooks.mjs", temp/"export_workbooks.mjs")
    font_dir=source_delivery/"inputs/fonts"
    node_env=os.environ.copy()
    if font_dir.exists():
        config=temp/"fonts.conf"
        config.write_text(f'<?xml version="1.0"?><!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd"><fontconfig><include ignore_missing="yes">/etc/fonts/fonts.conf</include><dir>{escape(str(font_dir))}</dir><cachedir>{escape(str(temp/"font-cache"))}</cachedir></fontconfig>')
        node_env["FONTCONFIG_FILE"]=str(config)
    def template(name):
        supplied=source_delivery/"inputs"/name.replace('.xlsx','_template.xlsx')
        return supplied if supplied.exists() else root/"A题/附件/附件3"/name
    if a.q4_json:
        previewdir=delivery/"validation/workbook_previews"; previewdir.mkdir(exist_ok=True)
        final=delivery/"output/result4.xlsx"
        with open(delivery/"validation/workbook_result4_build.log","w") as f:
            subprocess.run([node,"--max-old-space-size=2048",str(temp/"export_workbooks.mjs"),"--mode=q4",f"--root={root}",f"--input={a.q4_json.resolve()}",f"--out={final}",f"--font={a.font}",f"--previewDir={previewdir}"],cwd=temp,env=node_env,stdout=f,stderr=subprocess.STDOUT,check=True)
        source=json.loads(a.q4_json.read_text())
        report=validate_q4(final,source)
        report["input_json_sha256"]=sha(a.q4_json)
        report["template_sha256"]=sha(template('result4.xlsx'))
        sidecar=Path(str(final)+".inspect.ndjson")
        if sidecar.exists(): sidecar.replace(delivery/"validation/workbook_result4_inspect.ndjson")
        (delivery/"validation/workbook_result4.json").write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n")
        print(json.dumps({"stage":"result4_validated","report":report},ensure_ascii=False),flush=True)
        if not a.q2_npz: return
    if not a.q2_npz:
        p.error("--q2-npz or --q4-json is required")
    with np.load(a.q2_npz) as data:
        times=np.asarray(data["time_s"], dtype="<f8")
        profile=np.asarray(data["profile_TC"], dtype="<f8")
        radius=np.asarray(data["radius_cm"], dtype=float)
    assert profile.shape == (len(times),21,2)
    assert times[0]==0 and times[-1]==206906.76 and np.array_equal(times[1:-1], np.arange(1,206907))
    source_hash=sha(a.q2_npz); builder_hash=sha(source_delivery/"source/export_workbooks.mjs")
    metadata=temp/"q2_meta.json"
    if a.resume and metadata.exists():
        previous=json.loads(metadata.read_text())
        if previous.get("source_sha256")!=source_hash or previous.get("builder_sha256")!=builder_hash:
            raise ValueError("Resume cache belongs to different inputs or builder; omit --resume for a fresh rebuild")
    times.tofile(temp/"q2_time.f64"); profile.tofile(temp/"q2_profile.f64")
    metadata.write_text(json.dumps({"shape":profile.shape,"radius_cm":radius.tolist(),"source_sha256":source_hash,"builder_sha256":builder_hash}))
    chunks=[]; start=time.monotonic()
    previewdir=delivery/"validation/workbook_previews"; previewdir.mkdir(exist_ok=True)
    logdir=delivery/"validation/workbook_chunks"; logdir.mkdir(exist_ok=True)
    slots=threading.Condition(); active=0
    def make_chunk(lo):
        nonlocal active
        hi=min(lo+a.chunk_rows,len(times)); outfile=temp/f"q2_chunk_{lo}_{hi}.xlsx"
        logfile=logdir/f"q2_chunk_{lo}_{hi}.log"
        reusable=False
        if a.resume and outfile.exists():
            try:
                with zipfile.ZipFile(outfile) as z:
                    reusable=z.testzip() is None
            except zipfile.BadZipFile:
                reusable=False
        if not reusable:
            cmd=[node,"--max-old-space-size=4096",str(temp/"export_workbooks.mjs"),"--mode=q2chunk",f"--root={root}",f"--inputDir={temp}",f"--lo={lo}",f"--hi={hi}",f"--out={outfile}",f"--font={a.font}",f"--previewDir={previewdir}",f"--preview={'true' if lo==1 else 'false'}"]
            with slots:
                while True:
                    control=temp/"q2_workers.txt"
                    cap=min(a.workers,int(control.read_text().strip())) if control.exists() else a.workers
                    available=int(re.search(r"MemAvailable:\s+(\d+)",Path('/proc/meminfo').read_text())[1])/1024**2
                    if available<8: cap=1
                    if active<cap and available>4:
                        active+=1; break
                    slots.wait(timeout=5)
            try:
                with open(logfile,"w") as f:
                    subprocess.run(cmd,cwd=temp,env=node_env,stdout=f,stderr=subprocess.STDOUT,check=True)
            finally:
                with slots:
                    active-=1; slots.notify_all()
        print(json.dumps({"stage":"chunk_complete","lo":lo,"hi":hi,"elapsed_s":time.monotonic()-start}),flush=True)
        return lo,hi,outfile
    with ThreadPoolExecutor(max_workers=a.workers) as pool:
        for chunk in pool.map(make_chunk,range(1,len(times),a.chunk_rows)):
            chunks.append(chunk)
            if len(chunks)>1:
                with zipfile.ZipFile(chunks[0][2]) as first, zipfile.ZipFile(chunk[2]) as current:
                    verify_common_parts(first,current)
    final=delivery/"q123_closeout/result2.xlsx"
    package=combine_chunks(chunks,final)
    package.update({"input_npz_sha256":sha(a.q2_npz),"artifact_builder_sha256":sha(source_delivery/"source/export_workbooks.mjs"),"chunk_rows":a.chunk_rows,"elapsed_s":time.monotonic()-start})
    package["template_sha256"]=sha(template('result2.xlsx'))
    (delivery/"validation/workbook_packaging.json").write_text(json.dumps(package,ensure_ascii=False,indent=2)+"\n")
    report=validate_q2(final,times,profile,radius.tolist())
    (delivery/"validation/workbook_result2.json").write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n")
    print(json.dumps({"stage":"result2_validated","report":report},ensure_ascii=False),flush=True)


if __name__ == "__main__":
    main()
